
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EasyFramework.Edit
{
public sealed partial class Language : Luban.BeanBase
{
    public Language(JSONNode _buf) 
    {
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { var __json0 = _buf["array"]; if(!__json0.IsArray) { throw new SerializationException(); } Array = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Array.Add(__v0); }   }
    }

    public static Language DeserializeLanguage(JSONNode _buf)
    {
        return new Language(_buf);
    }

    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 英文描述
    /// </summary>
    public readonly System.Collections.Generic.List<string> Array;
   
    public const int __ID__ = -1548945544;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Lc tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "array:" + Luban.StringUtil.CollectionToString(Array) + ","
        + "}";
    }
}

}
