// <auto-generated>
// 此文件由 LC.UpdateLanguageConfig() 自动生成
// 请勿手动修改

namespace EasyFramework.Edit
{
	/// <summary> 编辑器语言键 </summary>
	public enum Lc
	{
		/// <summary> 分隔符 </summary>
		S,
		/// <summary> 全部 </summary>
		All,
		/// <summary> 添加 </summary>
		Add,
		/// <summary> 任何 </summary>
		Any,
		/// <summary> 自动 </summary>
		Auto,
		/// <summary> 轴 </summary>
		Axis,
		/// <summary> 音频 </summary>
		Audio,
		/// <summary> 异步 </summary>
		Async,
		/// <summary> 图集 </summary>
		Atlas,
		/// <summary> 等待 </summary>
		Await,
		/// <summary> 活跃 </summary>
		Active,
		/// <summary> 作者 </summary>
		Author,
		/// <summary> 资源 </summary>
		Assets,
		/// <summary> 缺失 </summary>
		Absent,
		/// <summary> 动画 </summary>
		Animat,
		/// <summary> 对齐 </summary>
		AlignAt,
		/// <summary> 已经 </summary>
		Already,
		/// <summary> 活动的 </summary>
		Activity,
		/// <summary> 放弃 </summary>
		Abandon,
		/// <summary> 按照 </summary>
		By,
		/// <summary> 绑定 </summary>
		Bind,
		/// <summary> 骨骼 </summary>
		Bone,
		/// <summary> 正在处理中... </summary>
		BeingProcessed,
		/// <summary> 可以 </summary>
		Can,
		/// <summary> 计算机处理器 </summary>
		CPU,
		/// <summary> 代码 </summary>
		Code,
		/// <summary> 清空 </summary>
		Clear,
		/// <summary> 类 </summary>
		Class,
		/// <summary> 链 </summary>
		Chain,
		/// <summary> 检查 </summary>
		Check,
		/// <summary> 颜色 </summary>
		Color,
		/// <summary> 关闭 </summary>
		Close,
		/// <summary> 数量 </summary>
		Count,
		/// <summary> 中心 </summary>
		Center,
		/// <summary> 取消 </summary>
		Cancel,
		/// <summary> 配置 </summary>
		Config,
		/// <summary> 创建 </summary>
		Create,
		/// <summary> 确认 </summary>
		Confirm,
		/// <summary> 列 </summary>
		Column,
		/// <summary> 自定义 </summary>
		Custom,
		/// <summary> 当前 </summary>
		Current,
		/// <summary> 内容 </summary>
		Content,
		/// <summary> 对比 </summary>
		Compare,
		/// <summary> 容量 </summary>
		Capacity,
		/// <summary> 倒计时 </summary>
		Countdown,
		/// <summary> 目录 </summary>
		Catalogue,
		/// <summary> 一致的 </summary>
		Consistency,
		/// <summary> 组件 </summary>
		Component,
		/// <summary> 压缩 </summary>
		Compression,
		/// <summary> 点 </summary>
		Dot,
		/// <summary> 数据 </summary>
		Data,
		/// <summary> 样品 </summary>
		Demo,
		/// <summary> 完成 </summary>
		Done,
		/// <summary> 向下 </summary>
		Down,
		/// <summary> 拖动 </summary>
		Drag,
		/// <summary> 停靠 </summary>
		Dock,
		/// <summary> 调试 </summary>
		Debug,
		/// <summary> 正在做 </summary>
		Doing,
		/// <summary> 延迟 </summary>
		Delay,
		/// <summary> 深度 </summary>
		Depth,
		/// <summary> 删除 </summary>
		Delete,
		/// <summary> 详情 </summary>
		Details,
		/// <summary> 销毁 </summary>
		Destroy,
		/// <summary> 设备 </summary>
		Device,
		/// <summary> 显示 </summary>
		Display,
		/// <summary> 禁用 </summary>
		Disable,
		/// <summary> 默认 </summary>
		Default,
		/// <summary> 动态 </summary>
		Dynamic,
		/// <summary> 下载 </summary>
		Download,
		/// <summary> 距离 </summary>
		Distance,
		/// <summary> 方向 </summary>
		Direction,
		/// <summary> 不同、差异 </summary>
		Different,
		/// <summary> 绘制次数 </summary>
		DrawCall,
		/// <summary> 解密 </summary>
		Decryption,
		/// <summary> 描述 </summary>
		Description,
		/// <summary> 减速 </summary>
		Deceleration,
		/// <summary> 结束 </summary>
		End,
		/// <summary> 退出 </summary>
		Exit,
		/// <summary> 边数 </summary>
		Edges,
		/// <summary> 空的 </summary>
		Empty,
		/// <summary> 错误 </summary>
		Error,
		/// <summary> 存在 </summary>
		Exist,
		/// <summary> 进入 </summary>
		Enter,
		/// <summary> 事件 </summary>
		Event,
		/// <summary> 编辑器 </summary>
		Editor,
		/// <summary> 启动 </summary>
		Enable,
		/// <summary> 相等 </summary>
		Equals,
		/// <summary> 元素 </summary>
		Element,
		/// <summary> 特效 </summary>
		Effects,
		/// <summary> 示例 </summary>
		Example,
		/// <summary> 提取 </summary>
		Extract,
		/// <summary> 加密 </summary>
		Encrypt,
		/// <summary> 异常 </summary>
		Exception,
		/// <summary> 执行 </summary>
		Execution,
		/// <summary> 弹性 </summary>
		Elasticity,
		/// <summary> 编辑器数据存档 </summary>
		EditorPrefs,
		/// <summary> 文件 </summary>
		File,
		/// <summary> 查找 </summary>
		Find,
		/// <summary> 折叠 </summary>
		Fold,
		/// <summary> 强制 </summary>
		Force,
		/// <summary> 找到 </summary>
		Found,
		/// <summary> 文件夹 </summary>
		Folder,
		/// <summary> 朋友 </summary>
		Friend,
		/// <summary> 筛选 </summary>
		Filtrate,
		/// <summary> 框架 </summary>
		Framework,
		/// <summary> 频繁 </summary>
		Frequently,
		/// <summary> 计算器显卡、图形处理器 </summary>
		GPU,
		/// <summary> 拥有、具备 </summary>
		Have,
		/// <summary> 提示 </summary>
		Hints,
		/// <summary> 高度 </summary>
		Height,
		/// <summary> 继续、等一等 </summary>
		Holdon,
		/// <summary> 硬件 </summary>
		Hardware,
		/// <summary> 强调 </summary>
		Highlight,
		/// <summary> 在...里 </summary>
		In,
		/// <summary> 标识码 </summary>
		Id,
		/// <summary> 是 </summary>
		Is,
		/// <summary> 空闲 </summary>
		Idle,
		/// <summary> 初始化 </summary>
		Init,
		/// <summary> 输入 </summary>
		Input,
		/// <summary> 安装 </summary>
		Install,
		/// <summary> 导入 </summary>
		Import,
		/// <summary> 惯性 </summary>
		Inertia,
		/// <summary> 实例 </summary>
		Instance,
		/// <summary> 间隔 </summary>
		Interval,
		/// <summary> 信息 </summary>
		Information,
		/// <summary> 键 </summary>
		Key,
		/// <summary> 列表 </summary>
		List,
		/// <summary> 左边 </summary>
		Left,
		/// <summary> 丢失 </summary>
		Lost,
		/// <summary> 加载 </summary>
		Load,
		/// <summary> 循环 </summary>
		Loop,
		/// <summary> 限制 </summary>
		Limit,
		/// <summary> 层 </summary>
		Layer,
		/// <summary> 级别 </summary>
		Level,
		/// <summary> 长、长度 </summary>
		Length,
		/// <summary> 语言 </summary>
		Language,
		/// <summary> 我的 </summary>
		My,
		/// <summary> 最小 </summary>
		Min,
		/// <summary> 最大 </summary>
		Max,
		/// <summary> 标记 </summary>
		Mark,
		/// <summary> 更多 </summary>
		More,
		/// <summary> 移动 </summary>
		Move,
		/// <summary> 匹配项 </summary>
		Match,
		/// <summary> 模型 </summary>
		Model,
		/// <summary> 鼠标 </summary>
		Mouse,
		/// <summary> 监控 </summary>
		Monitor,
		/// <summary> 缺失 </summary>
		Missing,
		/// <summary> 分钟 </summary>
		Minutes,
		/// <summary> 管理者 </summary>
		Manager,
		/// <summary> 内存 </summary>
		Memory,
		/// <summary> 上移 </summary>
		MoveUp,
		/// <summary> 下移 </summary>
		MoveDown,
		/// <summary> 手动 </summary>
		Manually,
		/// <summary> 材质球 </summary>
		Materials,
		/// <summary> 没有 </summary>
		No,
		/// <summary> 非 </summary>
		Non,
		/// <summary> 不 </summary>
		Not,
		/// <summary> 新 </summary>
		New,
		/// <summary> 名称 </summary>
		Name,
		/// <summary> 节点 </summary>
		Node,
		/// <summary> 命名空间 </summary>
		Namespace,
		/// <summary> 好的 </summary>
		Ok,
		/// <summary> 或 </summary>
		Or,
		/// <summary> .....的 </summary>
		Of,
		/// <summary> 老 </summary>
		Old,
		/// <summary> 一个 </summary>
		One,
		/// <summary> 打开 </summary>
		Open,
		/// <summary> 仅仅、只 </summary>
		Only,
		/// <summary> 其他 </summary>
		Other,
		/// <summary> 对象、物体 </summary>
		Object,
		/// <summary> 选项 </summary>
		Options,
		/// <summary> 总览 </summary>
		Overview,
		/// <summary> 占用 </summary>
		Occupancy,
		/// <summary> 覆写 </summary>
		Overwrite,
		/// <summary> 操作 </summary>
		Operating,
		/// <summary> 路径 </summary>
		Path,
		/// <summary> 打包 </summary>
		Pack,
		/// <summary> 池 </summary>
		Pool,
		/// <summary> 参数 </summary>
		Param,
		/// <summary> 面板 </summary>
		Panel,
		/// <summary> 父 </summary>
		Parent,
		/// <summary> 预制件 </summary>
		Prefab,
		/// <summary> 请 </summary>
		Please,
		/// <summary> 待 </summary>
		Pending,
		/// <summary> 插件 </summary>
		Plugins,
		/// <summary> 项目 </summary>
		Project,
		/// <summary> 粒子 </summary>
		Particle,
		/// <summary> 位置 </summary>
		Position,
		/// <summary> 包 </summary>
		Package,
		/// <summary> 进度 </summary>
		Progress,
		/// <summary> 流程 </summary>
		Procedure,
		/// <summary> 游戏存档 </summary>
		PlayerPrefs,
		/// <summary> 预设、偏好 </summary>
		Preferences,
		/// <summary> 查询 </summary>
		Query,
		/// <summary> 红 </summary>
		Red,
		/// <summary> 行 </summary>
		Row,
		/// <summary> 比率 </summary>
		Rate,
		/// <summary> 依赖 </summary>
		Rely,
		/// <summary> 根 </summary>
		Root,
		/// <summary> 右边 </summary>
		Right,
		/// <summary> 重置 </summary>
		Reset,
		/// <summary> 半径 </summary>
		Radius,
		/// <summary> 原因 </summary>
		Reason,
		/// <summary> 记录 </summary>
		Record,
		/// <summary> 反射 </summary>
		Reflect,
		/// <summary> 运行时 </summary>
		Running,
		/// <summary> 相关 </summary>
		Related,
		/// <summary> 刷新 </summary>
		Refresh,
		/// <summary> 请求 </summary>
		Request,
		/// <summary> 弧度 </summary>
		Radian,
		/// <summary> 去除、解除 </summary>
		Remove,
		/// <summary> 资源 </summary>
		Resource,
		/// <summary> 雷达图 </summary>
		RadarMap,
		/// <summary> 注册 </summary>
		Register,
		/// <summary> 渲染 </summary>
		Rendering,
		/// <summary> 重复 </summary>
		Repetition,
		/// <summary> 分辨率 </summary>
		Resolution,
		/// <summary> 尺寸 </summary>
		Size,
		/// <summary> 同步 </summary>
		Sync,
		/// <summary> 排序 </summary>
		Sort,
		/// <summary> 保存 </summary>
		Save,
		/// <summary> 自身 </summary>
		Self,
		/// <summary> 分数 </summary>
		Score,
		/// <summary> 场景 </summary>
		Scene,
		/// <summary> 状态 </summary>
		State,
		/// <summary> 速度、只表示大小，不涉及方向 </summary>
		Speed,
		/// <summary> 脚本 </summary>
		Script,
		/// <summary> 屏幕 </summary>
		Screen,
		/// <summary> 滚动 </summary>
		Scroll,
		/// <summary> 选择 </summary>
		Select,
		/// <summary> 服务器 </summary>
		Server,
		/// <summary> 系统 </summary>
		System,
		/// <summary> 开关 </summary>
		Switch,
		/// <summary> 源 </summary>
		Source,
		/// <summary> 间距 </summary>
		Spacing,
		/// <summary> 单一的 </summary>
		Simplex,
		/// <summary> 设置 </summary>
		Settings,
		/// <summary> 存活 </summary>
		Surviving,
		/// <summary> 挂起 </summary>
		Suspended,
		/// <summary> 滑动条 </summary>
		Scrollbar,
		/// <summary> 灵敏度 </summary>
		Sensitivity,
		/// <summary> 订阅 </summary>
		Subscriptions,
		/// <summary> 到 </summary>
		To,
		/// <summary> 太 </summary>
		Too,
		/// <summary> 时间 </summary>
		Time,
		/// <summary> 这个 </summary>
		This,
		/// <summary> 提示、便签 </summary>
		Tips,
		/// <summary> 任务 </summary>
		Task,
		/// <summary> 工具 </summary>
		Tool,
		/// <summary> 类型 </summary>
		Type,
		/// <summary> 树 </summary>
		Tree,
		/// <summary> 标题 </summary>
		Title,
		/// <summary> 总数 </summary>
		Total,
		/// <summary> 目标 </summary>
		Target,
		/// <summary> 材质、贴图 </summary>
		Texture,
		/// <summary> 超时 </summary>
		Timeout,
		/// <summary> 三角面 </summary>
		Triangular,
		/// <summary> 向上 </summary>
		Up,
		/// <summary> 用户 </summary>
		User,
		/// <summary> 使用 </summary>
		Use,
		/// <summary> 之下 </summary>
		Under,
		/// <summary> 更新 </summary>
		Update,
		/// <summary> 展开 </summary>
		Unfold,
		/// <summary> 更新中 </summary>
		Updating,
		/// <summary> 上传 </summary>
		Upload,
		/// <summary> 上传中 </summary>
		Uploading,
		/// <summary> 卸载 </summary>
		Unload,
		/// <summary> 值 </summary>
		Value,
		/// <summary> 顶点 </summary>
		Vertex,
		/// <summary> 供应商 </summary>
		Vendor,
		/// <summary> 版本 </summary>
		Version,
		/// <summary> 速度、包含了方向的信息 </summary>
		Velocity,
		/// <summary> 对于 </summary>
		With,
		/// <summary> 宽度 </summary>
		Width,
		/// <summary> 是的 </summary>
		Yes,
		/// <summary> 再试试 </summary>
		TryAgain,
		/// <summary> 好久不见 </summary>
		LongTimeNoSee,
		/// <summary> 请稍后 </summary>
		PleaseWaitMoment,
		/// <summary> 当前收集器中已经存在图集，请检查！ </summary>
		SC_AtlasExistInCollection,
		/// <summary> 图集已存在，是否覆盖？ </summary>
		SC_AtlasExistAlsoOverwrite,
		/// <summary> 存档数据 - 导入提示 </summary>
		Ppe_ImportHint,
		/// <summary> 存档数据 - 删除全部的提示 </summary>
		Ppe_DeleteAllHint,
		/// <summary> 存档数据 - 创建自定义提示 </summary>
		Ppe_CreateCustomHint,
		/// <summary> 递归查找, 资源过多时非常慢。 </summary>
		Stw_RecurseDependencies,
		/// <summary> 前缀 </summary>
		Prefix,
		/// <summary> 后缀 </summary>
		Suffix,
		/// <summary> 替换 </summary>
		Replace,
		/// <summary> 序号 </summary>
		Sequence,
		/// <summary> 预览 </summary>
		Preview,
		/// <summary> 应用 </summary>
		Apply,
		/// <summary> 步长 </summary>
		Step,
		/// <summary> 起始 </summary>
		Start,
		/// <summary> 补零 </summary>
		Padding,
		/// <summary> 冲突 </summary>
		Conflict,
		/// <summary> 跳过 </summary>
		Skip,
		/// <summary> 成功 </summary>
		Success,
		/// <summary> 失败 </summary>
		Failed,
		/// <summary> 着色器 </summary>
		Shader,
		/// <summary> 请在Project窗口选中资源，或点击刷新选中按钮 </summary>
		Artw_SelectAssetsHint,
		/// <summary> 重命名冲突，跳过 </summary>
		Artw_RenameConflictSkip,
		/// <summary> 重命名失败 </summary>
		Artw_RenameFailed,
		/// <summary> 没有需要重命名的资源 </summary>
		Artw_NoNeedRename,
		/// <summary> 模式 </summary>
		Mode,
		/// <summary> 文本 </summary>
		Text,
		/// <summary> 重命名 </summary>
		Rename,
		/// <summary> 替换为 </summary>
		Artw_ReplaceTo,
		/// <summary> 资源 </summary>
		Asset,
		/// <summary> 完成 </summary>
		Complete,
		/// <summary> 选项 </summary>
		Option,
	}
}
