
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace EasyFramework
{
public partial class LC
{
    public Example.TbItem TbItem {get; }

    public LC(System.Func<string, ByteBuf> loader)
    {
        TbItem = new Example.TbItem(loader("example_tbitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
    }
}

}
